"""Change domain model: entities, statuses, idempotency keys, run records (T-003)."""

from dark_factory.changes.enums import (
    BoundaryArea,
    ChangeRequestStatus,
    ChangeSource,
    DecisionClass,
    DecisionOutcome,
    DecisionSource,
    EscalationRule,
    EvidenceType,
    FindingOrigin,
    FindingSeverity,
    FindingStatus,
    Gate,
    GateStatus,
    HumanParticipation,
    ProductStatus,
    Provider,
    RiskClass,
    Role,
    Route,
    RunStatus,
    Stage,
    StageStatus,
    StopOutcome,
)
from dark_factory.changes.escalations import EscalationViolation
from dark_factory.changes.findings import Decision, Finding, GateResult
from dark_factory.changes.implementation_contract import (
    AcceptanceCriterion,
    ContractApproval,
    ContractBudget,
    ImplementationContract,
)
from dark_factory.changes.keys import attempt_id, effect_key, operation_key
from dark_factory.changes.next_action import (
    ExecuteStageAction,
    MergeAction,
    NextAction,
    ReleaseAction,
    RequestApprovalAction,
    ReworkAction,
    StopAction,
    WaitForCIAction,
    WaitForInputAction,
)
from dark_factory.changes.product import Product
from dark_factory.changes.refs import ArtifactRef, ChangeRequestRef, Evidence, RepositoryRef
from dark_factory.changes.run import (
    RETRYABLE_STAGE_STATUSES,
    RUN_STATUS_TRANSITIONS,
    RUN_TERMINAL_STATUSES,
    SCHEMA_VERSION,
    STAGE_STATUS_TRANSITIONS,
    STAGE_TERMINAL_STATUSES,
    Change,
    ChangeRun,
    InvalidStatusTransition,
    StageResult,
    StageRun,
    completion_violations,
)
from dark_factory.changes.run_records import (
    RunManifest,
    RunRecord,
    from_json,
    from_yaml,
    to_json,
    to_yaml,
)
from dark_factory.changes.usage import BudgetSnapshot, Usage

__all__ = [
    "RETRYABLE_STAGE_STATUSES",
    "RUN_STATUS_TRANSITIONS",
    "RUN_TERMINAL_STATUSES",
    "SCHEMA_VERSION",
    "STAGE_STATUS_TRANSITIONS",
    "STAGE_TERMINAL_STATUSES",
    "AcceptanceCriterion",
    "ArtifactRef",
    "BoundaryArea",
    "BudgetSnapshot",
    "Change",
    "ChangeRequestRef",
    "ChangeRequestStatus",
    "ChangeRun",
    "ChangeSource",
    "ContractApproval",
    "ContractBudget",
    "Decision",
    "DecisionClass",
    "DecisionOutcome",
    "DecisionSource",
    "EscalationRule",
    "EscalationViolation",
    "Evidence",
    "EvidenceType",
    "ExecuteStageAction",
    "Finding",
    "FindingOrigin",
    "FindingSeverity",
    "FindingStatus",
    "Gate",
    "GateResult",
    "GateStatus",
    "HumanParticipation",
    "ImplementationContract",
    "InvalidStatusTransition",
    "MergeAction",
    "NextAction",
    "Product",
    "ProductStatus",
    "Provider",
    "ReleaseAction",
    "RepositoryRef",
    "RequestApprovalAction",
    "ReworkAction",
    "RiskClass",
    "Role",
    "Route",
    "RunManifest",
    "RunRecord",
    "RunStatus",
    "Stage",
    "StageResult",
    "StageRun",
    "StageStatus",
    "StopAction",
    "StopOutcome",
    "Usage",
    "WaitForCIAction",
    "WaitForInputAction",
    "attempt_id",
    "completion_violations",
    "effect_key",
    "from_json",
    "from_yaml",
    "operation_key",
    "to_json",
    "to_yaml",
]
