"""Native SDD Core: ChangeSet artifacts, Product Baseline, adapters (ADR-020).

Single public surface of the SDD layer. Adapters here implement the port
structurally and never import ``dark_factory.ports``; the port re-exports the
domain types its signatures use.
"""

from dark_factory.changes.enums import RiskClass
from dark_factory.context.sdd.baseline import (
    BaselineFile,
    FactoryManifest,
    apply_delta_operations,
    compute_revision,
    current_revision,
    hash_bytes,
    init_baseline,
    read_factory_manifest,
    scan_baseline,
    write_factory_manifest,
    write_reconciliation_result,
)
from dark_factory.context.sdd.errors import (
    BaselineMismatchError,
    ChangeNotFoundError,
    FrontmatterError,
    MissingArtifactError,
    SDDError,
)
from dark_factory.context.sdd.frontmatter import (
    parse_frontmatter,
    render_document,
    split_frontmatter,
    validate_frontmatter,
    with_status,
)
from dark_factory.context.sdd.lifecycle import (
    CHANGESET_STATUS_TRANSITIONS,
    CHANGESET_TERMINAL_STATUSES,
    ChangeSetStatus,
    InvalidChangeSetStatus,
    validate_change_status_transition,
)
from dark_factory.context.sdd.models import (
    CHANGE_ID_PATTERN,
    CHANGE_SCHEMA,
    DESIGN_SCHEMA,
    EVIDENCE_INDEX_SCHEMA,
    RECONCILIATION_PLAN_SCHEMA,
    RECONCILIATION_RESULT_SCHEMA,
    TASK_GRAPH_SCHEMA,
    VERIFICATION_PLAN_SCHEMA,
    AddOperation,
    BaselineRef,
    ChangeManifest,
    CheckSpec,
    Delta,
    DeltaOperation,
    DeltaOperationKind,
    Document,
    EvidenceEntry,
    EvidenceIndex,
    EvidenceResult,
    Frontmatter,
    ModifyOperation,
    Owners,
    ReconciliationPlan,
    ReconciliationResult,
    RequirementVerification,
    RetireOperation,
    SupersedeOperation,
    TargetRef,
    TaskDef,
    TaskGraph,
    VerificationPlan,
    WorkflowRef,
)
from dark_factory.context.sdd.native import (
    NativeChangeSetAdapter,
    change_dir_name,
    next_change_id,
)
from dark_factory.context.sdd.normalized import (
    Axis,
    AxisFinding,
    ChangeSet,
    NormalizedChangeSet,
    RequirementEntry,
    RequirementsSnapshot,
    normalize,
)
from dark_factory.context.sdd.openspec import OpenSpecAdapter
from dark_factory.context.sdd.speckit import SpecKitAdapter
from dark_factory.context.sdd.strictness import (
    ArtifactSlot,
    WorkflowProfile,
    required_artifacts,
)

__all__ = [
    "CHANGESET_STATUS_TRANSITIONS",
    "CHANGESET_TERMINAL_STATUSES",
    "CHANGE_ID_PATTERN",
    "CHANGE_SCHEMA",
    "DESIGN_SCHEMA",
    "EVIDENCE_INDEX_SCHEMA",
    "RECONCILIATION_PLAN_SCHEMA",
    "RECONCILIATION_RESULT_SCHEMA",
    "TASK_GRAPH_SCHEMA",
    "VERIFICATION_PLAN_SCHEMA",
    "AddOperation",
    "ArtifactSlot",
    "Axis",
    "AxisFinding",
    "BaselineFile",
    "BaselineMismatchError",
    "BaselineRef",
    "ChangeManifest",
    "ChangeNotFoundError",
    "ChangeSet",
    "ChangeSetStatus",
    "CheckSpec",
    "Delta",
    "DeltaOperation",
    "DeltaOperationKind",
    "Document",
    "EvidenceEntry",
    "EvidenceIndex",
    "EvidenceResult",
    "FactoryManifest",
    "Frontmatter",
    "FrontmatterError",
    "InvalidChangeSetStatus",
    "MissingArtifactError",
    "ModifyOperation",
    "NativeChangeSetAdapter",
    "NormalizedChangeSet",
    "OpenSpecAdapter",
    "Owners",
    "ReconciliationPlan",
    "ReconciliationResult",
    "RequirementEntry",
    "RequirementVerification",
    "RequirementsSnapshot",
    "RetireOperation",
    "RiskClass",
    "SDDError",
    "SpecKitAdapter",
    "SupersedeOperation",
    "TargetRef",
    "TaskDef",
    "TaskGraph",
    "VerificationPlan",
    "WorkflowProfile",
    "WorkflowRef",
    "apply_delta_operations",
    "change_dir_name",
    "compute_revision",
    "current_revision",
    "hash_bytes",
    "init_baseline",
    "next_change_id",
    "normalize",
    "parse_frontmatter",
    "read_factory_manifest",
    "render_document",
    "required_artifacts",
    "scan_baseline",
    "split_frontmatter",
    "validate_change_status_transition",
    "validate_frontmatter",
    "with_status",
    "write_factory_manifest",
    "write_reconciliation_result",
]
