"""state schema

Revision ID: 0001_state_schema
Revises:
Create Date: 2026-09-13

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_state_schema"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "effect_ledger",
        sa.Column("effect_key", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("external_ref", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('planned', 'in_progress', 'succeeded', 'unknown')",
            name=op.f("ck_effect_ledger_status_allowed"),
        ),
        sa.PrimaryKeyConstraint("effect_key", name=op.f("pk_effect_ledger")),
    )
    op.create_table(
        "execution",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("change_id", sa.String(length=128), nullable=False),
        sa.Column("route", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("state_revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "provider IN ('gitlab', 'github')", name=op.f("ck_execution_provider_allowed")
        ),
        sa.CheckConstraint(
            "route IN ('quick', 'standard')", name=op.f("ck_execution_route_allowed")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'waiting', 'blocked', 'succeeded', 'failed', 'canceled', 'superseded')",
            name=op.f("ck_execution_status_allowed"),
        ),
        sa.CheckConstraint(
            "state_revision >= 1", name=op.f("ck_execution_state_revision_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution")),
    )
    op.create_index(op.f("ix_execution_change_id"), "execution", ["change_id"], unique=False)
    op.create_table(
        "execution_leases",
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=256), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("fencing_token", sa.Integer(), nullable=False),
        sa.Column(
            "acquired_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "heartbeat_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fencing_token >= 1", name=op.f("ck_execution_leases_fencing_token_positive")
        ),
        sa.PrimaryKeyConstraint("resource_type", "resource_id", name=op.f("pk_execution_leases")),
    )
    op.create_table(
        "outbox",
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("change_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("aggregate_version", sa.Integer(), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("causation_id", sa.String(length=128), nullable=True),
        sa.Column(
            "artifact_refs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "aggregate_version >= 1", name=op.f("ck_outbox_aggregate_version_positive")
        ),
        sa.CheckConstraint("event_version >= 1", name=op.f("ck_outbox_event_version_positive")),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_outbox_sequence_positive")),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_outbox")),
        sa.UniqueConstraint("aggregate_id", "sequence", name="aggregate_sequence"),
    )
    op.create_index(op.f("ix_outbox_change_id"), "outbox", ["change_id"], unique=False)
    op.create_index(
        "ix_outbox_change_id_sequence", "outbox", ["change_id", "sequence"], unique=False
    )
    op.create_index(op.f("ix_outbox_event_type"), "outbox", ["event_type"], unique=False)
    op.create_index(op.f("ix_outbox_run_id"), "outbox", ["run_id"], unique=False)
    op.create_index("ix_outbox_run_id_sequence", "outbox", ["run_id", "sequence"], unique=False)
    op.create_table(
        "event_delivery",
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("consumer_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=1024), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'delivered', 'failed', 'dead', 'waived')",
            name=op.f("ck_event_delivery_status_allowed"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_event_delivery_attempts_non_negative")),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["outbox.event_id"],
            name=op.f("fk_event_delivery_event_id_outbox"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", "consumer_id", name=op.f("pk_event_delivery")),
    )
    op.create_table(
        "stage",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("execution_id", sa.String(length=128), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("input_revision", sa.String(length=128), nullable=False),
        sa.Column("operation_key", sa.String(length=512), nullable=False),
        sa.Column("state_revision", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "stage IN ('specification', 'planning', 'construction', 'review_verification', 'release')",
            name=op.f("ck_stage_stage_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'in_progress', 'waiting', 'succeeded', 'failed', 'blocked', 'skipped', 'superseded', 'canceled')",
            name=op.f("ck_stage_status_allowed"),
        ),
        sa.CheckConstraint("attempt_count >= 0", name=op.f("ck_stage_attempt_count_non_negative")),
        sa.CheckConstraint("state_revision >= 1", name=op.f("ck_stage_state_revision_positive")),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["execution.id"],
            name=op.f("fk_stage_execution_id_execution"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage")),
        sa.UniqueConstraint("operation_key", name=op.f("uq_stage_operation_key")),
    )
    op.create_index(op.f("ix_stage_execution_id"), "stage", ["execution_id"], unique=False)
    op.create_table(
        "usage",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("execution_id", sa.String(length=128), nullable=False),
        sa.Column("attempt_id", sa.String(length=640), nullable=True),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("rework_rounds", sa.Integer(), nullable=False),
        sa.Column("manual_interventions", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completion_tokens >= 0", name=op.f("ck_usage_completion_tokens_non_negative")
        ),
        sa.CheckConstraint(
            "manual_interventions >= 0", name=op.f("ck_usage_manual_interventions_non_negative")
        ),
        sa.CheckConstraint("prompt_tokens >= 0", name=op.f("ck_usage_prompt_tokens_non_negative")),
        sa.CheckConstraint("rework_rounds >= 0", name=op.f("ck_usage_rework_rounds_non_negative")),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["execution.id"],
            name=op.f("fk_usage_execution_id_execution"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage")),
    )
    op.create_index(op.f("ix_usage_execution_id"), "usage", ["execution_id"], unique=False)
    op.create_table(
        "attempt",
        sa.Column("id", sa.String(length=640), nullable=False),
        sa.Column("operation_key", sa.String(length=512), nullable=False),
        sa.Column("stage_id", sa.String(length=256), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'in_progress', 'waiting', 'succeeded', 'failed', 'blocked', 'skipped', 'superseded', 'canceled')",
            name=op.f("ck_attempt_status_allowed"),
        ),
        sa.CheckConstraint("attempt_number >= 1", name=op.f("ck_attempt_attempt_number_positive")),
        sa.ForeignKeyConstraint(
            ["stage_id"], ["stage.id"], name=op.f("fk_attempt_stage_id_stage"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt")),
        sa.UniqueConstraint("stage_id", "attempt_number", name="stage_number"),
    )
    op.create_index(op.f("ix_attempt_operation_key"), "attempt", ["operation_key"], unique=False)
    op.create_index(op.f("ix_attempt_stage_id"), "attempt", ["stage_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attempt_stage_id"), table_name="attempt")
    op.drop_index(op.f("ix_attempt_operation_key"), table_name="attempt")
    op.drop_table("attempt")
    op.drop_index(op.f("ix_usage_execution_id"), table_name="usage")
    op.drop_table("usage")
    op.drop_index(op.f("ix_stage_execution_id"), table_name="stage")
    op.drop_table("stage")
    op.drop_table("event_delivery")
    op.drop_index("ix_outbox_run_id_sequence", table_name="outbox")
    op.drop_index(op.f("ix_outbox_run_id"), table_name="outbox")
    op.drop_index(op.f("ix_outbox_event_type"), table_name="outbox")
    op.drop_index("ix_outbox_change_id_sequence", table_name="outbox")
    op.drop_index(op.f("ix_outbox_change_id"), table_name="outbox")
    op.drop_table("outbox")
    op.drop_table("execution_leases")
    op.drop_index(op.f("ix_execution_change_id"), table_name="execution")
    op.drop_table("execution")
    op.drop_table("effect_ledger")
    # ### end Alembic commands ###
