"""Bounded rework loop policy: review -> rework -> re-review (T-014, FR-008, ADR-018 p.5).

The loop level above the flow transitions. The flow
(``dark_factory.orchestration.flow``) applies an accepted ``ReworkAction``:
it spends one rework round through ``dark_factory.orchestration.rules.limits`` and sends
the work to the rework target stage. This module adds the loop-level policy
decision the flow does not make: after a completed review pass, is one more
rework round worth spending, or does the loop stop in ``Blocked`` with
human-readable diagnostics?

Pure and deterministic — no harness/LLM/clock/database; identical inputs
yield an identical decision. ``quality`` is not imported: the loop consumes
finding signatures the caller derived from the review classification, so the
dependency direction quality -> flow stays intact.

The loop history is append-only (FR-008, ADR-018 p.5): a new attempt appends
a new ``ReviewPass`` and never rewrites the previous ones. Decisions about
past passes are never reused as an acceptance — the verdict of every pass is
valid for its own SHA only (T-020: a new SHA invalidates the previous
acceptance), and the repeat check below is a stop condition, not a tolerance.

Stop conditions, in deterministic order, first match -> ``Blocked`` (a subset
of the ADR-018 p.5 escalation conditions):

- a declared escalation on the last pass — an escalation is not a rework
  iteration, the limit is not spent; a requirements conflict
  (``REQUIREMENTS_DEFICIENT``) stops here;
- the rework limit, via ``rework_violation`` (FR-016: the budget counters
  are the authority on the rounds already spent);
- no new commit: the last pass ran at the previous pass's SHA, so re-review
  cannot invalidate the standing acceptance;
- a repeated error: the blocking finding set did not change after rework.
"""

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from dark_factory.changes.enums import FindingOrigin
from dark_factory.changes.escalations import EscalationViolation
from dark_factory.changes.findings import Finding
from dark_factory.changes.usage import BudgetSnapshot
from dark_factory.orchestration.policy.escalation import escalation_stop_reason
from dark_factory.orchestration.rules.limits import rework_violation


@dataclass(frozen=True)
class FindingSignature:
    """Hashable identity of a blocking finding, stable across review passes.

    Built from the ``Finding`` fields that survive a rework round: ``id`` is
    regenerated by every review pass and ``reviewed_sha`` changes with every
    round, so neither takes part in the identity (T-020: findings of a new
    SHA are new findings).
    """

    origin: FindingOrigin
    category: str | None
    file: str | None
    line: int | None


def finding_signature(finding: Finding) -> FindingSignature:
    """Identity of ``finding`` for loop bookkeeping: (origin, category, file, line)."""
    return FindingSignature(
        origin=finding.origin,
        category=finding.category,
        file=finding.file,
        line=finding.line,
    )


def _sort_key(signature: FindingSignature) -> tuple[str, str, str, int]:
    """Deterministic total order over signatures for stable diagnostics."""
    return (
        signature.origin.value,
        signature.category or "",
        signature.file or "",
        signature.line or 0,
    )


def _render(signature: FindingSignature) -> str:
    """One-line rendering of a signature for the human-readable reason."""
    category = signature.category if signature.category is not None else "-"
    file = signature.file if signature.file is not None else "-"
    line = str(signature.line) if signature.line is not None else "-"
    return f"{signature.origin.value}/{category} {file}:{line}"


class ReviewPass(BaseModel):
    """One completed review pass in the append-only loop history (T-014).

    ``round`` is the loop round of the pass: 1 for the initial review, and
    ``k + 1`` for the re-review that follows rework round ``k``. ``blocking``
    holds the signatures of the findings that failed the pass; ``escalations``
    lists the violations declared on the pass (ADR-018 p.5).
    """

    model_config = ConfigDict(frozen=True)

    round: int = Field(ge=1)
    sha: str = Field(min_length=1)
    blocking: tuple[FindingSignature, ...] = ()
    escalations: list[EscalationViolation] = []


@dataclass(frozen=True)
class ReworkDecision:
    """Loop-level verdict after one completed review pass (T-014).

    ``outcome="rework"`` spends ``round`` (``budget.used_rework_rounds + 1``)
    and re-enters the loop; ``outcome="blocked"`` stops the loop — ``round``
    is ``None`` and ``reason`` carries the diagnostics for a human.
    ``signatures`` are the sorted blocking signatures of the last pass.
    """

    outcome: Literal["rework", "blocked"]
    round: int | None
    max_rounds: int
    reason: str
    signatures: tuple[FindingSignature, ...]


def plan_rework(*, budget: BudgetSnapshot, passes: Sequence[ReviewPass]) -> ReworkDecision:
    """Decide the next loop step after the last completed review pass.

    ``passes`` is the append-only history of completed review passes in
    execution order; the last element is the pass that has just finished.
    The function is pure: neither ``budget`` nor ``passes`` is mutated, and
    identical inputs yield an identical decision.

    The loop is planned only for a failed review: an empty history and a last
    pass without blocking findings raise ``ValueError`` (a passed review
    continues through the flow, not through this policy). Past passes are
    never re-judged and never reinstate an acceptance: only the last pass is
    decided on, and its verdict is valid for its ``sha`` only.

    Stop conditions, in deterministic order, first match -> ``blocked``
    (details in the module docstring):

    1. escalations declared on the last pass (``escalation_stop_reason``);
    2. the rework limit (``rework_violation`` with
       ``requested_round = budget.used_rework_rounds + 1``);
    3. the last two passes ran at the same SHA — re-review is impossible;
    4. the last two passes blocked on the same finding set — repeated error;
    5. otherwise one more round is planned: ``round = used + 1`` and the
       reason enumerates the blocking findings, sorted by
       ``(origin, category, file, line)``.
    """
    if not passes:
        raise ValueError(
            "no completed review pass in the history: "
            "the rework loop is planned after a failed review"
        )
    last = passes[-1]
    signatures = tuple(sorted(last.blocking, key=_sort_key))
    if not signatures:
        raise ValueError(
            f"review pass {last.round} at {last.sha} has no blocking findings: "
            "the rework loop is planned only for a failed review"
        )
    escalation_reason = escalation_stop_reason(last.escalations)
    if escalation_reason is not None:
        return _blocked(budget, escalation_reason, signatures)
    next_round = budget.used_rework_rounds + 1
    violation = rework_violation(budget, requested_round=next_round)
    if violation is not None:
        return _blocked(budget, violation.reason, signatures)
    if len(passes) >= 2:
        previous = passes[-2]
        if previous.sha == last.sha:
            return _blocked(
                budget,
                (
                    f"rework did not produce a new commit: review pass {last.round} ran again "
                    f"at {last.sha}; the previous acceptance of that SHA stands, "
                    "re-review is impossible"
                ),
                signatures,
            )
        if frozenset(previous.blocking) == frozenset(signatures):
            return _blocked(
                budget,
                (
                    f"rework round {last.round - 1} did not change the set of blocking "
                    f"findings: the same {len(signatures)} finding(s) repeat"
                ),
                signatures,
            )
    reason = (
        f"rework round {next_round}: fix {len(signatures)} blocking finding(s) "
        f"from review pass {last.round} at {last.sha}: "
        + "; ".join(_render(signature) for signature in signatures)
    )
    return ReworkDecision(
        outcome="rework",
        round=next_round,
        max_rounds=budget.max_rework_rounds,
        reason=reason,
        signatures=signatures,
    )


def _blocked(
    budget: BudgetSnapshot, reason: str, signatures: tuple[FindingSignature, ...]
) -> ReworkDecision:
    """Terminal ``blocked`` decision of the loop with the last pass's findings."""
    return ReworkDecision(
        outcome="blocked",
        round=None,
        max_rounds=budget.max_rework_rounds,
        reason=reason,
        signatures=signatures,
    )
