#!/usr/bin/env bash
# Install Argo CD and the root Applications (T032, ADR-010/ADR-015):
#   1. helm upgrade --install argocd argo/argo-cd (chart version pinned below,
#      values from values-argocd.yaml — quota-aware, dex/notifications off);
#   2. helm upgrade --install dark-factory-argocd-apps (local chart in chart/)
#      rendering the `factory` platform Application and the `apps-dev`
#      app-of-apps Application.
#
# Secrets are NEVER created here (nothing secret lives in git):
#   - the admin password is auto-generated by the chart (argocd-secret,
#     created by the redis-secret-init hook job outside helm release state);
#   - credentials for a PRIVATE dark-factory-gitops repo must be created as
#     the `dark-factory-gitops-repo-creds` secret (outside git) — without it
#     the install continues and the `apps-dev` application stays in an error
#     state with a precise remediation hint (pattern of deploy/ci, T030).
#
# Prerequisites: deploy/bootstrap (T029) already applied — namespace `argocd`
# with quotas/NetworkPolicies exists.
#
# Usage: install.sh [--context NAME] [--gitops-repo-url URL]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source-path=SCRIPTDIR
source "$SCRIPT_DIR/scripts/common.sh"

# Pinned upstream chart: 10.9.1 = Argo CD 3.5.3 (inspected 2026-09-14).
# Upgrade = bump this constant in a reviewed MR, never a floating version.
ARGOCD_CHART_VERSION="10.9.1"
ARGO_HELM_REPO_URL="https://argoproj.github.io/argo-helm"

require_cmds kubectl helm git

GITOPS_REPO_URL="https://github.com/vadagama/dark-factory-gitops.git"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --context) KUBECTL_CTX="${2:-}"; shift 2 ;;
    --gitops-repo-url) GITOPS_REPO_URL="${2:-}"; shift 2 ;;
    -h|--help) grep '^# ' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

if ! cluster_reachable; then
  k8s_disabled_hint
  exit 1
fi

# --- Prerequisites from the bootstrap (T029) ---------------------------------
kctl get namespace argocd >/dev/null 2>&1 \
  || die "namespace 'argocd' not found — run deploy/bootstrap/bootstrap.sh first"

# --- Idempotent helm install of Argo CD ---------------------------------------
info "adding/updating the argo helm repository"
helm repo add argo "$ARGO_HELM_REPO_URL" --force-update >/dev/null
helm repo update argo >/dev/null

info "installing Argo CD (chart argo/argo-cd $ARGOCD_CHART_VERSION) into namespace argocd"
helm --namespace argocd upgrade --install argocd argo/argo-cd \
  --version "$ARGOCD_CHART_VERSION" \
  -f "$SCRIPT_DIR/values-argocd.yaml" \
  --wait --timeout 10m

# --- Warnings for out-of-git state (remediation pattern of T030) --------------
if ! kctl -n argocd get secret dark-factory-gitops-repo-creds >/dev/null 2>&1; then
  warn "secret 'dark-factory-gitops-repo-creds' does not exist in namespace 'argocd'."
  warn "It is required ONLY if the GitOps repository is private (recommended):"
  warn "  kubectl -n argocd create secret generic dark-factory-gitops-repo-creds \\"
  warn "    --from-literal=type=git \\"
  warn "    --from-literal=url=$GITOPS_REPO_URL \\"
  warn "    --from-literal=username=<github-username> \\"
  warn "    --from-literal=password=<read-only PAT (contents:read)>"
  warn "  kubectl -n argocd label secret dark-factory-gitops-repo-creds argocd.argoproj.io/secret-type=repository"
  warn "For a public repository this secret is not needed; the install continues either way."
fi

if ! GIT_TERMINAL_PROMPT=0 git -c http.lowSpeedLimit=1 -c http.lowSpeedTime=15 \
  ls-remote --exit-code "$GITOPS_REPO_URL" HEAD >/dev/null 2>&1; then
  warn "GitOps repository $GITOPS_REPO_URL is not reachable (does not exist yet or is private without creds)."
  warn "The 'apps-dev' application will stay in an error state until the repository is bootstrapped:"
  warn "  1. push the seed from deploy/argocd/gitops-seed/ (exact commands: gitops-seed/README.md);"
  warn "  2. create the repo-creds secret above if the repository is private."
  warn "Creating the GitHub repository is a human decision (no gh create from agents)."
  warn "Continuing with the install; see deploy/argocd/README.md for the first-live-run procedure."
fi

# --- Idempotent helm install of the root Applications --------------------------
# Applied after the Argo CD release so the Application CRDs exist.
info "registering root Applications (factory, apps-dev) via the local chart"
helm --namespace argocd upgrade --install dark-factory-argocd-apps "$SCRIPT_DIR/chart" \
  --set gitopsRepoURL="$GITOPS_REPO_URL"

# --- Status report (non-fatal) -------------------------------------------------
info "registered Applications:"
kctl -n argocd get applications -o custom-columns='NAME:.metadata.name,SYNC:.status.sync.status,HEALTH:.status.health.status' \
  2>/dev/null || warn "applications CRD not ready yet — re-run install.sh or wait a moment"

ok "install complete. Next steps:"
ok "  1. ./verify.sh --context $KUBECTL_CTX"
ok "  2. UI: kubectl -n argocd port-forward svc/argocd-server 8080:8080"
ok "     login: admin / \$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d)"
